
[workspace]
members = ['apps/client', 'libs/copper', 'libs/tauri_plugin_copper']
resolver = "2"

[workspace.dependencies]
serde_json = "1.0.105"
serde = { version = "1.0, < 1.0.172", features = ["derive"] }
tauri = { version = "1.4.1", features = [] }

[profile.release]
lto = true
