name: Build

on:
  create:
    tag:
      - "v*"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  runs-on: ubuntu-18.04
  run:
    shell: bash

jobs:
  build:
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --immutable

      - name: Lint
        run: yarn lint:all

      - name: Test
        run: yarn test:all

      - name: Build
        run: |
          yarn clean:all
          yarn build:all

      # -------------------------------------------------------------------------
      # PUBLISHING TO NPM
      # -------------------------------------------------------------------------
      # One-time steps to setup publishing:
      # 1. Uncomment the Publish step below and change __PACKAGE_NAME__ to the name of
      #    the package you want to publish. (Include the @scope, if any.)
      # 2. Create a secret in your github repo named NPM_TOKEN to authenticate to npm.
      #
      # To publish a version (replace "1.2.3" with your version number), run:
      #     yarn version:all 1.2.3
      #     git push --follow-tags
      #
      # See https://github.com/jtbennett/create-ts-project/blob/main/docs/publishing-to-npm.md
      # for details.
      # -------------------------------------------------------------------------
      # - name: Publish
      #   if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      #   env:
      #     YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: |
      #     yarn workspace __PACKAGE_NAME__ npm publish --access public
