// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	header: {
		accountDropdown: {
			/**
			 * C​r​e​a​t​e​ ​a​c​c​o​u​n​t
			 */
			createAccount: string
			/**
			 * N​o​ ​a​c​c​o​u​n​t​ ​s​e​l​e​c​t​e​d
			 */
			noAccount: string
			/**
			 * S​e​t​t​i​n​g​s
			 */
			settings: string
		}
		/**
		 * Q​u​i​c​k​ ​s​e​a​r​c​h​ ​(​c​t​r​l​ ​+​ ​k​)
		 */
		quickSearch: string
	}
}

export type TranslationFunctions = {
	header: {
		accountDropdown: {
			/**
			 * Create account
			 */
			createAccount: () => LocalizedString
			/**
			 * No account selected
			 */
			noAccount: () => LocalizedString
			/**
			 * Settings
			 */
			settings: () => LocalizedString
		}
		/**
		 * Quick search (ctrl + k)
		 */
		quickSearch: () => LocalizedString
	}
}

export type Formatters = {}
