/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__(cmd: string, args?: Record<string, unknown>): Promise<any>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export async function testConnection(): Promise<null> {
return await invoke()("plugin:copper|test_connection");
}


